version: "3"
tasks:
  run:
    cmds:
      - go run ./cmd/authzsvc
  tidy:
    cmds:
      - go mod tidy
  build:
    cmds:
      - go build -o bin/authz ./cmd/authzsvc
  up:
    cmds:
      - docker compose up --build
