package integration

import (
	"context"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/you/authzsvc/domain"
	"github.com/you/authzsvc/internal/mocks"
	"github.com/you/authzsvc/internal/services"
)

// TestAuditLoggingIntegration verifies that audit logging works end-to-end
// during password change operations for CB-183 compliance
func TestAuditLoggingIntegration(t *testing.T) {
	t.Parallel()

	// Create comprehensive audit service with real audit repository mock
	auditRepo := mocks.NewMockAuditRepository()
	var capturedEvents []*domain.ComprehensiveAuditEvent
	
	// Configure audit repository to capture events
	auditRepo.CreateFunc = func(ctx context.Context, event *domain.ComprehensiveAuditEvent) error {
		// Set correlation ID like the real repository would
		if event.CorrelationID == uuid.Nil {
			event.SetCorrelationID()
		}
		capturedEvents = append(capturedEvents, event)
		return nil
	}

	// Create audit service with mock repository
	auditService := services.NewComprehensiveAuditService(
		auditRepo,
		nil, // encryptor
		nil, // integrityChecker
		nil, // asyncProcessor
		nil, // metrics
		nil, // exporter
		nil, // config
		nil, // logger
	)

	// Test 1: Audit logging during successful password change initiation
	t.Run("successful_password_change_initiation_audit", func(t *testing.T) {
		userID := uint(123)
		requestID := "test-request-123"
		ipAddress := "192.168.1.100"
		userAgent := "Test-Agent/1.0"

		// Execute audit logging
		err := auditService.LogPasswordChangeInitiated(context.Background(), userID, requestID, ipAddress, userAgent)
		if err != nil {
			t.Fatalf("Failed to log password change initiation: %v", err)
		}

		// Verify audit event was captured
		if len(capturedEvents) != 1 {
			t.Fatalf("Expected 1 audit event, got %d", len(capturedEvents))
		}

		event := capturedEvents[0]
		
		// Verify audit event structure
		if event.EventType != domain.EventTypePasswordChangeInitiated {
			t.Errorf("Expected event type %s, got %s", domain.EventTypePasswordChangeInitiated, event.EventType)
		}
		
		if event.EventCategory != domain.CategoryAuthentication {
			t.Errorf("Expected category %s, got %s", domain.CategoryAuthentication, event.EventCategory)
		}
		
		if event.UserID == nil || *event.UserID != userID {
			t.Errorf("Expected user ID %d, got %v", userID, event.UserID)
		}
		
		if event.IPAddress != ipAddress {
			t.Errorf("Expected IP address %s, got %s", ipAddress, event.IPAddress)
		}
		
		if event.UserAgent != userAgent {
			t.Errorf("Expected user agent %s, got %s", userAgent, event.UserAgent)
		}
		
		if !event.Success {
			t.Error("Expected success to be true for initiation")
		}
		
		if event.Action != "password_change_initiate" {
			t.Errorf("Expected action 'password_change_initiate', got %s", event.Action)
		}

		// Verify LGPD/GDPR compliance fields
		if event.LegalBasis != domain.LegalBasisLegitimateInterests {
			t.Errorf("Expected legal basis %s, got %s", domain.LegalBasisLegitimateInterests, event.LegalBasis)
		}
		
		if event.DataClassification != domain.DataClassificationConfidential {
			t.Errorf("Expected data classification %s, got %s", domain.DataClassificationConfidential, event.DataClassification)
		}
		
		if event.RetentionPolicy != domain.RetentionPolicyLong {
			t.Errorf("Expected retention policy %s, got %s", domain.RetentionPolicyLong, event.RetentionPolicy)
		}

		// Verify metadata structure
		if event.Metadata == nil {
			t.Error("Expected metadata to be present")
		}

		// Verify correlation ID is set (note: it should be auto-generated by the repository)
		if event.CorrelationID == uuid.Nil {
			t.Errorf("Expected correlation ID to be set, got: %s", event.CorrelationID.String())
		}

		// Verify timestamp is reasonable
		if time.Since(event.Timestamp) > time.Minute {
			t.Error("Expected timestamp to be recent")
		}

		t.Logf("✅ Password change initiation audit event verified successfully")
	})

	// Reset captured events for next test
	capturedEvents = []*domain.ComprehensiveAuditEvent{}

	// Test 2: Audit logging during password change completion
	t.Run("successful_password_change_completion_audit", func(t *testing.T) {
		userID := uint(456)
		requestID := "test-request-456"
		ipAddress := "10.0.0.50"
		userAgent := "Mobile-App/2.1"

		// Execute audit logging
		err := auditService.LogPasswordChangeCompleted(context.Background(), userID, requestID, ipAddress, userAgent)
		if err != nil {
			t.Fatalf("Failed to log password change completion: %v", err)
		}

		// Verify audit event was captured
		if len(capturedEvents) != 1 {
			t.Fatalf("Expected 1 audit event, got %d", len(capturedEvents))
		}

		event := capturedEvents[0]
		
		// Verify completion-specific audit event structure
		if event.EventType != domain.EventTypePasswordChangeCompleted {
			t.Errorf("Expected event type %s, got %s", domain.EventTypePasswordChangeCompleted, event.EventType)
		}
		
		if event.Action != "password_change_complete" {
			t.Errorf("Expected action 'password_change_complete', got %s", event.Action)
		}
		
		if !event.Success {
			t.Error("Expected success to be true for completion")
		}

		t.Logf("✅ Password change completion audit event verified successfully")
	})

	// Reset captured events for next test
	capturedEvents = []*domain.ComprehensiveAuditEvent{}

	// Test 3: Audit logging during password change failure
	t.Run("password_change_failure_audit", func(t *testing.T) {
		userID := uint(789)
		requestID := "test-request-789"
		reason := "Invalid OTP code"
		ipAddress := "172.16.0.10"
		userAgent := "Web-Browser/1.0"

		// Execute audit logging for failure
		err := auditService.LogPasswordChangeFailed(context.Background(), &userID, requestID, reason, ipAddress, userAgent)
		if err != nil {
			t.Fatalf("Failed to log password change failure: %v", err)
		}

		// Verify audit event was captured
		if len(capturedEvents) != 1 {
			t.Fatalf("Expected 1 audit event, got %d", len(capturedEvents))
		}

		event := capturedEvents[0]
		
		// Verify failure-specific audit event structure
		if event.EventType != domain.EventTypePasswordChangeFailed {
			t.Errorf("Expected event type %s, got %s", domain.EventTypePasswordChangeFailed, event.EventType)
		}
		
		if event.Action != "password_change_fail" {
			t.Errorf("Expected action 'password_change_fail', got %s", event.Action)
		}
		
		if event.Success {
			t.Error("Expected success to be false for failure")
		}
		
		if event.ErrorDetails != reason {
			t.Errorf("Expected error details %s, got %s", reason, event.ErrorDetails)
		}

		t.Logf("✅ Password change failure audit event verified successfully")
	})

	// Reset captured events for next test
	capturedEvents = []*domain.ComprehensiveAuditEvent{}

	// Test 4: Audit logging during password change expiration
	t.Run("password_change_expiration_audit", func(t *testing.T) {
		userID := uint(101)
		requestID := "test-request-expired"
		ipAddress := "203.0.113.5"
		userAgent := "API-Client/3.0"

		// Execute audit logging for expiration
		err := auditService.LogPasswordChangeExpired(context.Background(), userID, requestID, ipAddress, userAgent)
		if err != nil {
			t.Fatalf("Failed to log password change expiration: %v", err)
		}

		// Verify audit event was captured
		if len(capturedEvents) != 1 {
			t.Fatalf("Expected 1 audit event, got %d", len(capturedEvents))
		}

		event := capturedEvents[0]
		
		// Verify expiration-specific audit event structure
		if event.EventType != domain.EventTypePasswordChangeExpired {
			t.Errorf("Expected event type %s, got %s", domain.EventTypePasswordChangeExpired, event.EventType)
		}
		
		if event.Action != "password_change_expire" {
			t.Errorf("Expected action 'password_change_expire', got %s", event.Action)
		}
		
		if event.Success {
			t.Error("Expected success to be false for expiration")
		}

		t.Logf("✅ Password change expiration audit event verified successfully")
	})

	// Reset captured events for next test
	capturedEvents = []*domain.ComprehensiveAuditEvent{}

	// Test 5: Audit logging during password change cancellation
	t.Run("password_change_cancellation_audit", func(t *testing.T) {
		userID := uint(202)
		requestID := "test-request-cancelled"
		ipAddress := "198.51.100.20"
		userAgent := "Desktop-App/4.2"

		// Execute audit logging for cancellation
		err := auditService.LogPasswordChangeCancelled(context.Background(), userID, requestID, ipAddress, userAgent)
		if err != nil {
			t.Fatalf("Failed to log password change cancellation: %v", err)
		}

		// Verify audit event was captured
		if len(capturedEvents) != 1 {
			t.Fatalf("Expected 1 audit event, got %d", len(capturedEvents))
		}

		event := capturedEvents[0]
		
		// Verify cancellation-specific audit event structure
		if event.EventType != domain.EventTypePasswordChangeCancelled {
			t.Errorf("Expected event type %s, got %s", domain.EventTypePasswordChangeCancelled, event.EventType)
		}
		
		if event.Action != "password_change_cancel" {
			t.Errorf("Expected action 'password_change_cancel', got %s", event.Action)
		}
		
		if !event.Success {
			t.Error("Expected success to be true for cancellation")
		}

		t.Logf("✅ Password change cancellation audit event verified successfully")
	})

	t.Logf("🎉 ALL AUDIT LOGGING INTEGRATION TESTS PASSED")
	t.Logf("📊 Verified 5 password change audit event types")
	t.Logf("🔒 Confirmed LGPD/GDPR compliance fields")
	t.Logf("✅ CB-183 audit logging integration is working correctly")
}

// TestPasswordChangeServiceAuditIntegration tests the actual integration
// between password change service and audit logging
func TestPasswordChangeServiceAuditIntegration(t *testing.T) {
	t.Parallel()

	// Create mock dependencies
	passwordChangeRepo := mocks.NewMockPasswordChangeRepository()
	passwordHistoryRepo := mocks.NewMockPasswordHistoryRepository()
	forgotPasswordRepo := mocks.NewMockForgotPasswordRepository()
	userRepo := mocks.NewMockUserRepository()
	passwordService := mocks.NewMockPasswordService()
	otpService := mocks.NewMockOTPService()
	sessionRepo := mocks.NewMockSessionRepository()

	// Create audit service with event capture
	auditRepo := mocks.NewMockAuditRepository()
	var capturedAuditEvents []*domain.ComprehensiveAuditEvent
	
	auditRepo.CreateFunc = func(ctx context.Context, event *domain.ComprehensiveAuditEvent) error {
		// Set correlation ID like the real repository would
		if event.CorrelationID == uuid.Nil {
			event.SetCorrelationID()
		}
		capturedAuditEvents = append(capturedAuditEvents, event)
		return nil
	}

	auditService := services.NewComprehensiveAuditService(
		auditRepo, nil, nil, nil, nil, nil,
		nil, // config
		nil, // logger
	)

	// Create password change service with audit integration
	config := services.DefaultPasswordChangeConfig()
	passwordChangeService := services.NewPasswordChangeService(
		passwordChangeRepo,
		passwordHistoryRepo,
		forgotPasswordRepo,
		userRepo,
		passwordService,
		otpService,
		sessionRepo,
		auditService,
		config,
	)

	// Test: Password change initiation with audit logging
	t.Run("password_change_initiation_with_audit", func(t *testing.T) {
		// Setup mocks for successful initiation
		userRepo.FindByIDFunc = func(ctx context.Context, id uint) (*domain.User, error) {
			return &domain.User{
				ID:           1,
				Email:        "user@example.com",
				PasswordHash: "old_hash",
				IsActive:     true,
			}, nil
		}

		passwordService.VerifyFunc = func(hashedPassword, password string) bool {
			// Return true only for the current password verification
			return hashedPassword == "old_hash" && password == "current_password"
		}

		passwordService.HashFunc = func(password string) (string, error) {
			return "new_hashed_password", nil
		}

		passwordHistoryRepo.GetRecentPasswordsFunc = func(ctx context.Context, userID uint, count int) ([]string, error) {
			return []string{"different_old_hash"}, nil // No password reuse
		}

		passwordChangeRepo.GetActiveByUserIDFunc = func(ctx context.Context, userID uint) (*domain.PasswordChangeRequest, error) {
			return nil, nil // No active request
		}

		passwordChangeRepo.CountRecentByUserIDFunc = func(ctx context.Context, userID uint, since time.Time) (int64, error) {
			return 0, nil // Within rate limit
		}

		passwordChangeRepo.CreateFunc = func(ctx context.Context, request *domain.PasswordChangeRequest) error {
			return nil // Request created successfully
		}

		otpService.GenerateFunc = func(ctx context.Context, phone string, userID uint) (*domain.OTPRequest, error) {
			return &domain.OTPRequest{
				Phone: phone,
				Code:  "123456",
			}, nil
		}

		// Execute password change initiation
		response, err := passwordChangeService.InitiatePasswordChange(
			context.Background(),
			1,                      // userID
			"current_password",     // currentPassword
			"NewPassword123!@#",    // newPassword (stronger password)
			"NewPassword123!@#",    // confirmPassword
			"192.168.1.100",       // ipAddress
			"Integration-Test/1.0", // userAgent
		)

		// Verify operation succeeded
		if err != nil {
			t.Fatalf("Password change initiation failed: %v", err)
		}

		if response == nil {
			t.Fatal("Expected response, got nil")
		}

		if response.Status != "initiated" {
			t.Errorf("Expected status 'initiated', got %s", response.Status)
		}

		// Verify audit event was logged
		if len(capturedAuditEvents) != 1 {
			t.Fatalf("Expected 1 audit event, got %d", len(capturedAuditEvents))
		}

		auditEvent := capturedAuditEvents[0]
		if auditEvent.EventType != domain.EventTypePasswordChangeInitiated {
			t.Errorf("Expected audit event type %s, got %s", 
				domain.EventTypePasswordChangeInitiated, auditEvent.EventType)
		}

		if auditEvent.UserID == nil || *auditEvent.UserID != 1 {
			t.Errorf("Expected audit user ID 1, got %v", auditEvent.UserID)
		}

		if auditEvent.IPAddress != "192.168.1.100" {
			t.Errorf("Expected audit IP address '192.168.1.100', got %s", auditEvent.IPAddress)
		}

		if auditEvent.UserAgent != "Integration-Test/1.0" {
			t.Errorf("Expected audit user agent 'Integration-Test/1.0', got %s", auditEvent.UserAgent)
		}

		t.Logf("✅ Password change service audit integration verified successfully")
		t.Logf("📝 Audit event captured: %s", auditEvent.EventType)
		t.Logf("🔐 User ID: %d, IP: %s", *auditEvent.UserID, auditEvent.IPAddress)
	})

	t.Logf("🎉 PASSWORD CHANGE SERVICE AUDIT INTEGRATION VERIFIED")
	t.Logf("✅ End-to-end audit logging is working correctly")
}